// ---------------------------------------------------------------------------
// generate-words.ts — reads placeholder-words.md and produces src/core/data/words.ts
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type WordLevel = 'primary' | 'middle';

interface WordEntry {
  english: string;
  chinese: string;
  level: WordLevel;
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const MD_PATH = resolve(import.meta.dirname, 'placeholder-words.md');
const OUT_PATH = resolve(import.meta.dirname, '..', 'src', 'core', 'data', 'words.ts');

// ---------------------------------------------------------------------------
// Parse markdown
// ---------------------------------------------------------------------------

function parseWords(md: string): { primary: WordEntry[]; middle: WordEntry[] } {
  const primary: WordEntry[] = [];
  const middle: WordEntry[] = [];

  let currentSection: 'primary' | 'middle' | null = null;

  const lines = md.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();

    if (trimmed === '## Primary') {
      currentSection = 'primary';
      continue;
    }
    if (trimmed === '## Middle') {
      currentSection = 'middle';
      continue;
    }

    // Parse "english | chinese | difficulty"
    const match = trimmed.match(/^-\s+(.+?)\s*\|\s*(.+?)\s*\|\s*(\d+)\s*$/);
    if (match && currentSection) {
      const entry: WordEntry = {
        english: match[1].trim(),
        chinese: match[2].trim(),
        level: currentSection,
      };
      if (currentSection === 'primary') {
        primary.push(entry);
      } else {
        middle.push(entry);
      }
    }
  }

  return { primary, middle };
}

// ---------------------------------------------------------------------------
// Generate words (pad to 1600: 1-505 primary, 506-1600 middle)
// ---------------------------------------------------------------------------

function generateWords(samples: { primary: WordEntry[]; middle: WordEntry[] }): WordEntry[] {
  const TOTAL = 1600;
  const PRIMARY_COUNT = 505;
  const MIDDLE_COUNT = TOTAL - PRIMARY_COUNT; // 1095

  const words: WordEntry[] = [];

  // Primary: ids 1-505
  for (let i = 0; i < PRIMARY_COUNT; i++) {
    if (i < samples.primary.length) {
      words.push({ ...samples.primary[i] });
    } else {
      const n = i + 1;
      words.push({
        english: `word_${n}`,
        chinese: `单词_${n}`,
        level: 'primary',
      });
    }
  }

  // Middle: ids 506-1600
  for (let i = 0; i < MIDDLE_COUNT; i++) {
    if (i < samples.middle.length) {
      words.push({ ...samples.middle[i] });
    } else {
      const n = PRIMARY_COUNT + i + 1;
      words.push({
        english: `word_${n}`,
        chinese: `单词_${n}`,
        level: 'middle',
      });
    }
  }

  return words;
}

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------

function writeWordsFile(words: WordEntry[]): void {
  const lines: string[] = [
    '// ---------------------------------------------------------------------------',
    '// Word Data — auto-generated by scripts/generate-words.ts',
    '// DO NOT EDIT MANUALLY',
    '// ---------------------------------------------------------------------------',
    "import type { Word } from './types';",
    '',
    `export const WORDS: Word[] = [`,
  ];

  for (const w of words) {
    lines.push(`  { english: ${JSON.stringify(w.english)}, chinese: ${JSON.stringify(w.chinese)}, level: ${JSON.stringify(w.level)} },`);
  }

  lines.push('];');
  lines.push('');

  // Ensure output directory exists
  const outDir = dirname(OUT_PATH);
  mkdirSync(outDir, { recursive: true });

  writeFileSync(OUT_PATH, lines.join('\n'), 'utf-8');
  console.log(`✓ Wrote ${words.length} words to ${OUT_PATH}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const md = readFileSync(MD_PATH, 'utf-8');
  const samples = parseWords(md);

  console.log(`Parsed ${samples.primary.length} primary samples, ${samples.middle.length} middle samples`);

  const words = generateWords(samples);
  writeWordsFile(words);

  const primaryWords = words.filter((w) => w.level === 'primary').length;
  const middleWords = words.filter((w) => w.level === 'middle').length;
  console.log(`Generated ${primaryWords} primary + ${middleWords} middle = ${words.length} total words`);
}

main();
