// ---------------------------------------------------------------------------
// generate-words.ts — reads the merged word list markdown (完整合并版)
// and produces src/core/data/words.ts
// ---------------------------------------------------------------------------
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type WordLevel = 'primary' | 'middle';

interface WordEntry {
  english: string;
  chinese: string;
  level: WordLevel;
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

const SRC_MD = resolve(import.meta.dirname, '..', 'words', '2022新课标_中英词汇对照表_完整合并版.md');
const OUT_PATH = resolve(import.meta.dirname, '..', 'src', 'core', 'data', 'words.ts');

// ---------------------------------------------------------------------------
// Parse markdown table into WordEntry[]
// ---------------------------------------------------------------------------

/**
 * Clean an English word for storage.
 * - Remove leading/trailing whitespace
 * - Collapse spaces
 */
function cleanEnglish(raw: string): string {
  return raw.trim().replace(/\s+/g, ' ');
}

/**
 * Get the primary English form (the first part before any parentheses variants).
 * e.g. "a (an)" → "a", "colour (AmE color)" → "colour"
 */
function primaryForm(raw: string): string {
  const cleaned = cleanEnglish(raw);
  // Remove "(...)" variants
  return cleaned.replace(/\s*\(.*?\)\s*/g, '').trim();
}

function parseWords(md: string): WordEntry[] {
  const wordMap = new Map<string, WordEntry>(); // key=english, value=lowest level
  const seen = new Set<string>();

  const lines = md.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();

    // Match table data rows: | level | english | pos | chinese |
    if (!trimmed.startsWith('|')) continue;
    const parts = trimmed.split('|').map(s => s.trim()).filter(Boolean);
    if (parts.length < 4) continue;

    const rawLevel = parts[0];
    const rawEnglish = parts[1];
    const meaning = parts[3]; // chinese meaning

    // Skip table header rows
    if (rawLevel === '级别' || rawLevel === '---') continue;
    if (rawEnglish === '单词' || rawEnglish === '---') continue;
    if (!rawLevel || !rawEnglish || !meaning) continue;

    let isPrimary: boolean;
    if (rawLevel.includes('二级') || rawLevel.includes('小学')) {
      isPrimary = true;
    } else if (rawLevel.includes('三级') || rawLevel.includes('初中')) {
      isPrimary = false;
    } else {
      continue;
    }

    const english = primaryForm(rawEnglish);
    if (!english) continue;
    const chinese = meaning.trim();

    // If word already exists, keep the lower level (primary < middle)
    const existing = wordMap.get(english);
    if (existing) {
      if (isPrimary && existing.level === 'middle') {
        // Upgrade to primary
        wordMap.set(english, { english, chinese, level: 'primary' });
      }
      // otherwise keep existing (if both are same level, keep first)
    } else {
      wordMap.set(english, {
        english,
        chinese,
        level: isPrimary ? 'primary' : 'middle',
      });
    }
  }

  return Array.from(wordMap.values());
}

// ---------------------------------------------------------------------------
// Assign difficulty based on word length and level
// ---------------------------------------------------------------------------

function getDifficulty(word: string, level: WordLevel, i: number): 1 | 2 | 3 {
  if (level === 'primary') return 1;
  // For middle level: longer words = harder
  if (word.length > 8) return 3;
  if (word.length > 5) return 2;
  // Mix shorter middle words: some 2, some 1
  return (i % 3 === 0) ? 3 : 2;
}

// ---------------------------------------------------------------------------
// Write output
// ---------------------------------------------------------------------------

function writeWordsFile(words: WordEntry[]): void {
  const lines: string[] = [
    '// ---------------------------------------------------------------------------',
    '// Word Data — auto-generated by scripts/generate-words.ts',
    '// Source: 2022新课标_中英词汇对照表_完整合并版.md',
    '// DO NOT EDIT MANUALLY — run `npx tsx scripts/generate-words.ts` to regenerate',
    '// ---------------------------------------------------------------------------',
    "import type { Word } from './types';",
    '',
    '// prettier-ignore',
    `export const WORDS: Word[] = [`,
  ];

  for (let i = 0; i < words.length; i++) {
    const w = words[i];
    const id = i + 1;
    const difficulty = getDifficulty(w.english, w.level, i);
    const imagePath = `/assets/images/word-images/${w.level}/${w.english}.png`;

    lines.push(`  {`);
    lines.push(`    id: ${id},`);
    lines.push(`    english: ${JSON.stringify(w.english)},`);
    lines.push(`    chinese: ${JSON.stringify(w.chinese)},`);
    lines.push(`    level: ${JSON.stringify(w.level)},`);
    lines.push(`    difficulty: ${difficulty},`);
    lines.push(`    imagePath: ${JSON.stringify(imagePath)},`);
    lines.push(`    correctCount: 0,`);
    lines.push(`    wrongCount: 0,`);
    lines.push(`    lastSeenAt: 0,`);
    lines.push(`  },`);
  }

  lines.push('];');
  lines.push('');

  // Ensure output directory exists
  const outDir = dirname(OUT_PATH);
  mkdirSync(outDir, { recursive: true });

  writeFileSync(OUT_PATH, lines.join('\n'), 'utf-8');
  console.log(`✓ Wrote ${words.length} words to ${OUT_PATH}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const md = readFileSync(SRC_MD, 'utf-8');
  const words = parseWords(md);

  const primaryWords = words.filter((w) => w.level === 'primary');
  const middleWords = words.filter((w) => w.level === 'middle');
  console.log(`Parsed ${words.length} unique words (${primaryWords.length} primary, ${middleWords.length} middle)`);

  writeWordsFile(words);

  console.log(`Done — ${words.length} words total (primary: ${primaryWords.length}, middle: ${middleWords.length})`);
}

main();
